//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.27 at 01:04:21 PM IST 
//


package com.stack.parser.tags;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="row" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                 &lt;attribute name="TagName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="Count" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *                 &lt;attribute name="ExcerptPostId" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                 &lt;attribute name="WikiPostId" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "row"
})
@XmlRootElement(name = "tags")
public class Tags {

    protected List<Tags.Row> row;

    /**
     * Gets the value of the row property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the row property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRow().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tags.Row }
     * 
     * 
     */
    public List<Tags.Row> getRow() {
        if (row == null) {
            row = new ArrayList<Tags.Row>();
        }
        return this.row;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
     *       &lt;attribute name="TagName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="Count" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
     *       &lt;attribute name="ExcerptPostId" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
     *       &lt;attribute name="WikiPostId" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Row {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "Id")
        protected Short id;
        @XmlAttribute(name = "TagName")
        protected String tagName;
        @XmlAttribute(name = "Count")
        protected Byte count;
        @XmlAttribute(name = "ExcerptPostId")
        protected Short excerptPostId;
        @XmlAttribute(name = "WikiPostId")
        protected Short wikiPostId;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setId(Short value) {
            this.id = value;
        }

        /**
         * Gets the value of the tagName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTagName() {
            return tagName;
        }

        /**
         * Sets the value of the tagName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTagName(String value) {
            this.tagName = value;
        }

        /**
         * Gets the value of the count property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getCount() {
            return count;
        }

        /**
         * Sets the value of the count property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setCount(Byte value) {
            this.count = value;
        }

        /**
         * Gets the value of the excerptPostId property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getExcerptPostId() {
            return excerptPostId;
        }

        /**
         * Sets the value of the excerptPostId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setExcerptPostId(Short value) {
            this.excerptPostId = value;
        }

        /**
         * Gets the value of the wikiPostId property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getWikiPostId() {
            return wikiPostId;
        }

        /**
         * Sets the value of the wikiPostId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setWikiPostId(Short value) {
            this.wikiPostId = value;
        }

    }

}
